### ISSUE TITLE
Extra content in bin/exiftool directory

### ISSUE THREAD

**Issue by philmoz** [musselwhizzle/Focus-Points#108]
The files/folders listed below aren't needed for the exiftool runtime in the bin directory. As far as I can tell there are no constraints/restrictions on including exiftool that would require these to be included. This would trim 10MB from the plugin.
- arg_files
- Changes
- config_files
- fmt_files
- html
- Makefile.PL
- MANIFEST
- META.json
- META.yml
- perl-Image-ExifTool.spec
- t

**Comment by musselwhizzle** [comment]
nice catch. please feel free to remove whatever is not needed for both windows and mac.

**Comment by musselwhizzle** [comment]
I've assigned to you if you'd like to do a PR. If not, I'd be happy to take it. 
Thanks again.
