### ISSUE TITLE
Unknown key: "orientation"

### ISSUE THREAD

**Issue by Knubbel** [musselwhizzle/Focus-Points#113]
Wanted to test the plugin on windows. Metadata display works fine.
But impossible to show focus points, as there is an internal error pop-up "Unknown key: "orientation""
Used zip file from entry screen downloaded some minutes ago.

**Comment by musselwhizzle** [comment]
It cause you're using LR 5. I'm not sure if there's a way to sniff out the version of LR or not. Will take a look.

**Comment by musselwhizzle** [comment]
fixed in the current master.
