### ISSUE TITLE
'*' in Pentax mapping files

### ISSUE THREAD

**Issue by ropma** [musselwhizzle/Focus-Points#141]
Some Pentax mapping files contain an invalid character. '*' is not supported on  Windows files systems.

Even if the is not an issue for the currently supported platform Mac, this is a prerequisite for the Windows version I'm working on.

Pull request is coming.

**Comment by musselwhizzle** [comment]
Thanks for the changes. I was just looking last night at the code and was planning out my attack again for windows. If you're tackling it, i can hold off.

**Comment by ropma** [comment]
Yes, I already have a first version using mogrify to do the rendering under Windows.
Some more testing is needed

**Comment by musselwhizzle** [comment]
in terms of the structure, hopefully we can just make https://github.com/musselwhizzle/Focus-Points/blob/master/focuspoints.lrdevplugin/DefaultPointRenderer.lua#L188 just return the correct view based upon the OS. I think that's probably the best place to patch the code in.
