### ISSUE TITLE
White Screen and Focal Point

### ISSUE THREAD

**Issue by Paul1762** [musselwhizzle/Focus-Points#146]
Fuji X-Pro2 - Lightroom CC.

I have installed the PlugIn, however when I active it to show the Focal Point, the image is covered with a white screen and the focal point is shown.

is this expected?

Paul

**Comment by musselwhizzle** [comment]
you were most likely on windows which hasn't been supported previously (it only worked on mac). deleted the plugin completely from your computer, remove it from lightroom, and then get the latest version. It now has windows support.
