### ISSUE TITLE
fails with olympus .orf files from em1 mark2 as well as nikon z7 .nef files

### ISSUE THREAD

**Issue by bwanaaa** [musselwhizzle/Focus-Points#148]
<img width="868" alt="Screen Shot 2019-11-04 at 7 15 56 PM" src="https://user-images.githubusercontent.com/4876720/68168697-a51df980-ff37-11e9-843b-0c0dba73f036.png">
<img width="774" alt="Screen Shot 2019-11-04 at 7 17 06 PM" src="https://user-images.githubusercontent.com/4876720/68168730-c7b01280-ff37-11e9-8884-b172479c8a8f.png">

It does show the metadata from these files.
And it DOES work with Fuji x100f .raf files.

**Comment by musselwhizzle** [comment]
that's not this project. you're welcome to try this one.

**Comment by bwanaaa** [comment]
sorry i initially posted the wrong screenshot.

**Comment by bwanaaa** [comment]
OS is MacBook pro running Mojave

**Comment by musselwhizzle** [comment]
can you zip and attach the files in question?

**Comment by bwanaaa** [comment]
thank you for reopening this issue. I also tried it on a win 10 pro machine with Lightroom 8.3. same results. Both of the raw files in this archive can be opened and edited in lightroom. However the plugin starts to calculate the focus point, a progress bar appears and then I get the 'no joy' dialog.
The files are big (because they are the original raws). Here is a link to a dropbox archive
https://www.dropbox.com/s/xg4je3udm83nm95/raw%20files.zip?dl=0

**Comment by capricorn8** [comment]
I cannot open the dropbox link. ("404  Diese Datei befindet sich nicht mehr an diesem Speicherort.")

Have you checked the "Show Metadata" output? I
n particular, "AF" related fields and further down in the list, Focus Mode".

**Comment by bwanaaa** [comment]
Sorry about that. Dropbox never synced the zip. Here is a direct link to one of the raw files that I AM SURE is there

https://www.dropbox.com/s/j5db2sbm82vdvlx/_A180118.ORF?dl=0

Exactly where are these checkboxes? No dialog is produced by the plugin with them.

**Comment by capricorn8** [comment]
No problem; I now could download the file.
When referring to "Show Metadata" I was talking about the second function of this plugin which is a plain textual report of EXIF metadata that reflect how the camera was configured while capturing the image. 

![image](https://user-images.githubusercontent.com/33000800/68226264-0efad980-fff2-11e9-9586-4acee915f412.png)

This is very helpful to figure out why an AF point cannot be diplayed. In your case:
AF Areas = none
AF Point Selected = n/a
AF Ready = Not Ready
which suggests that for this image you have pressed the shutter before focusing was complete.  

@musselwhizzle:
In case the "focus point not found" dialog pops up it would be nice to have the option to directly proceed to "Show Metadata" and figure out why the plugin is not able to do its job.  This could also prevent new users from hastily reporting errors.

**Comment by musselwhizzle** [comment]
Good idea @capricorn8

**Comment by bwanaaa** [comment]
ok. Well look at this raw file.

https://www.dropbox.com/s/jonfygar2feaim6/DSC_0001.NEF?dl=0

The metadata show an autofocus point
<img width="784" alt="Screen Shot 2019-11-05 at 6 52 22 PM" src="https://user-images.githubusercontent.com/4876720/68256300-b29db700-fffd-11e9-93f0-0edb913415b4.png">
but the plugin still fails
<img width="872" alt="Screen Shot 2019-11-05 at 6 52 45 PM" src="https://user-images.githubusercontent.com/4876720/68256310-be897900-fffd-11e9-8edb-20386129b9f4.png">

**Comment by bwanaaa** [comment]
btw, here is the focus point that nikon nx-d software properly shows in dark magenta as a square in the image

<img width="641" alt="Screen Shot 2019-11-05 at 6 59 02 PM" src="https://user-images.githubusercontent.com/4876720/68256568-95b5b380-fffe-11e9-9d2b-c7302a688865.png">

**Comment by ropma** [comment]
The EXIF data contains Live View Focus Points ("AF Area xx") and also the "Primary AF Point":

11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Area Height' = '324' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Area Mode' = 'Single' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Area Width' = '292' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Area X Position' = '2568' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Area Y Position' = '2168' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Fine Tune' = 'Off' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Fine Tune Adj' = '0' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Fine Tune Index' = 'n/a' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Image Height' = '5504' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Image Width' = '8256' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Info 2 Version' = '0300' 
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'AF Points Used' = '(none)' 
..
11/07/2019 22:38:09 DEBUG	           EXIFUTILS | Parsed 'Primary AF Point' = 'C6 (Center)' 

In the algorithm the "Primary AF Point" has priority over the live view AF points. As the is no mapping file for the Z 7 the display of the primary AF point (C6)  fails.

According to the screenshot above the Live View focus point was used (and not the center point)

For testing I've commented out the handling of the "Primary AF Point" and get now the same result as the Nikon Software:

![image](https://user-images.githubusercontent.com/37225368/68431292-22ed3980-01b2-11ea-91e3-c3c6a4c4d347.png)

Maybe for the Z7 the live view AF points should have priority of the Primary AF point? But I don't have a Z7, thus I can't do more tests.

**Comment by musselwhizzle** [comment]
@bwanaaa - looks like the real issue is your camera isn't listed in the supported cameras. You're welcome to follow the steps on how to making a mapping file. Unfortunately, Nikon's focus points aren't given dynamically like every other manufacture. 

https://github.com/musselwhizzle/Focus-Points#adding-your-own-camera

**Comment by bwanaaa** [comment]
@ropma 
Thank you!
I looked in the file \Focus-Points-master\focuspoints.lrdevplugin\bin\exiftool\lib\Image\ExifTool\Nikon.pm
and found numerous references to the variable 'PrimaryAFPoint'

At line 3433 I found thiis

         Name => 'PrimaryAFPoint',
            Condition => '$$self{AFInfo2Version} eq "0100"',
            Notes => 'future models?...',
            PrintConv => {
                0 => '(none)',
                1 => 'Center',
            },
        },
 
Is this the section you commented out(deleted)?
I could find no reference to a ' Live View focus point'

**Comment by ropma** [comment]
@bwanaaa 

No! 

Line 86 in /Focus-Points/focuspoints.lrdevplugin/DefaultDelegates.lua :

`--  local selectedPoint = ExifUtils.findFirstMatchingValue(metaData, DefaultDelegates.metaKeyAfPointSelected)
`

Please keep in mind: this will BREAK at least the support of Nikon DSLRs. And I don't know if it works with other shots / focus modes of the Z7.

For further analysis: could you provide three more shots with your Nikon Z 7? First with the focus point in the middle, second with the focus point in the upper left corner and third in the lower right corner.

**Comment by musselwhizzle** [comment]
close ticketing. Resolution: camera is just not supported. We welcome @bwanaaa to read the README and add the camera supporting.
