### ISSUE TITLE
Suggestion: Enhanced EXIF data browsing

### ISSUE THREAD

**Issue by capricorn8** [musselwhizzle/Focus-Points#156]
I'm using this plug-in on a daily basis, and I found myself using the EXIF part increasingly more often than the focus part.

One thing that would significantly improve user experience while browsing EXIF data would be a more sophisticated window that allows for searching tag names, rather than copy and paste the entire text to an editor and search there. If you happen to know the exact tag name, you can find it by scrolling (even that could be accelerated by searching), but if you don't there is no way around copy-paste-search.

Does the window object used by the plugin support searching?
If not is there any alternative that could be used?

**Comment by musselwhizzle** [comment]
Great idea. It's probably possible to add that search feature to the window. Feel free to create a PR to add the feature!

**Comment by capricorn8** [comment]
I will look what I can do, but very likely this will be beyond my capabilities. My career as a SW developer has ended 20y ago...

If somebody has some tipps on the exercise (see above questions), these are highly welcome.

**Comment by capricorn8** [comment]
With the advise from John R Ellis from the Adobe LrC forum, I have been able to add a filter to the metadata dialog, as well as an extra button to open the metadata as a .txt file.

It's working fine for me on Windows; I don't have the chance to test it on Mac.
Also, I'm not familiar with Github as a CM system.

If there is someone who is willing to check this out on Mac, and support with adding this new feature to Github, that would be great!

For now, I'm attaching the modified files (all changes have been marked accordingly).

Here is a screenshot of the enhanced dialog:

![Metadata display](https://user-images.githubusercontent.com/33000800/114936219-684c7680-9e3c-11eb-8805-95a2142528da.jpg)

[ChangedFiles.zip](https://github.com/musselwhizzle/Focus-Points/files/6321048/ChangedFiles.zip)

**Comment by capricorn8** [comment]
@musselwhizzle 

I have never worked with Github, so I'm not sure whether my pull request #160 has ended up in the right place, and includes the proper information (4 updated files, as included in the zip files attached to the previous post).

If you like this improvement and want to merge it to the main branch, I could update the readme as well, if you want me to.

**Comment by musselwhizzle** [comment]
Hi @capricorn8 - you did it correctly, but the pull request has not been closed. If you reopen it, I can review it and commit the changes.
