### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Andygeol** [musselwhizzle/Focus-Points#157]
I was able to ADD the plugin but when I go to Plugin extras, there is nothing there.
Using LR classic v.10.2.

![lr PI Manager](https://user-images.githubusercontent.com/83865760/117536614-ea6f2b80-aff3-11eb-9169-deb4e7835ff1.JPG)
![lr PI ManagerPLUGIN EXTRAS](https://user-images.githubusercontent.com/83865760/117536715-96b11200-aff4-11eb-9ec3-cc0105ba2ac1.JPG)

Andy Holmes

**Comment by capricorn8** [comment]
Not sure why this is, but on my system (Win10 + LR CC) I can't see the plug-in under File -> Plug-in Extras but only under Library -> Plug-in Extras.

**Comment by Andygeol** [comment]
Thanks Karsten, I get the same  !

Andy Holmes

**Comment by Laddyacris** [comment]
Hello @Andygeol @capricorn8 
You need to go Library Menu > Plug-in extras > Show Focus Point 
Enjoy !

**Comment by musselwhizzle** [comment]
Based upon @Laddyacris comment, I'm resolving the issue. Please reopen @Andygeol if this does not fix your issue
