### ISSUE TITLE
Improved support for Sony RX10M4

### ISSUE THREAD

**Issue by jodaco67** [musselwhizzle/Focus-Points#159]
The results for my RX10M4 seemed inaccurate and the active focus point never aligned to one of the pdaf points. There is a windows program called AFV (https://github.com/SK-Hardwired/s_afv) that shows different results. Comparing the algorithms I think the approach in that program is better since it doesn't require arbitrary parameters like pdafScale but instead exclusively uses image geometry. I applied this to my own code and it works very nicely and now the in-focus points almost always aligns with one of the pdaf points. I still need to implement face and animal eye notation but I can do that later. 

Since I only have a RX10M4 and no other Sony cameras I can't be sure this works in all cases so I created a SonyRX10M4Delegates and modified the PointsRendererFactory accordingly. I don't see any other model specific delegates so I'm not certain this is the correct approach. I'm happy to share my code with the community if these changes are acceptable.

**Comment by musselwhizzle** [comment]
Hi, Would you mind creating a pull request with your changes!?

**Comment by jodaco67** [comment]
Please forgive my ignorance. I created a branch in GitHub Desktop called '159' (my issue number) but when I try to create a pull request it says I must publish. When i try to do that it says I do not have write permissions. I tried the commands in Contributing.md but I'm getting various errors there too.

**Comment by musselwhizzle** [comment]
If you can zip up the contents and attach them here, I can add the code.

**Comment by musselwhizzle** [comment]
https://github.com/musselwhizzle/Focus-Points/pull/161

Merged
