### ISSUE TITLE
Update exiftool to latest version (Dec. 20, 2024 - Version 13.10) for WIN and MAC

### ISSUE THREAD

**Issue by capricorn8** [musselwhizzle/Focus-Points#188]
Version 13.10 is the most recent production release and contains many improvements (support of new cameras, lenses, tags) as well as a changed structure for the Windows executable (https://oliverbetz.de/pages/Artikel/ExifTool-for-Windows).

**Comment by musselwhizzle** [comment]
Hi Capricorn8, I will merge this Merge Request now. I've added you as a "maintainer" to this project. So I believe in the future you should have the power to merge and close tickets.
