### ISSUE TITLE
Plugin menu does not show up

### ISSUE THREAD

**Issue by rderimay** [musselwhizzle/Focus-Points#2]
The plugin is correctly recognized and activated but to menu item shows up in the Lightroom > Plugins - Extras menu :-(

**Comment by musselwhizzle** [comment]
see screenshot on how to access it. 

<img width="833" alt="screen shot 2017-01-03 at 10 10 09 am" src="https://cloud.githubusercontent.com/assets/2308674/21617844/eb554c9e-d19c-11e6-8274-328e7050a61c.png">
