### ISSUE TITLE
An internal error occured: **[string "DefaulDelegates.lua"]:55: attempt to index local 'selectedFocusPoint' (a nil value)

### ISSUE THREAD

**Issue by Knubbel** [musselwhizzle/Focus-Points#20]
Using latest windows-fix branch on windows.
Used test file http://216.18.212.226/PRODS/canon-80d/FULLRES/YIMG_1587-ISO100.JPG

Error:
"An internal error occured: **[string "DefaultDelegates.lua"]:55: attempt to index local 'selectedFocusPoint' (a nil value)**"

**Comment by rderimay** [comment]
I'll work on this

**Comment by musselwhizzle** [comment]
You have a windows machine to test? Basically the plugin on seems to work on Mac. For some reasons it seems that exif tool is not generating on windows.

**Comment by rderimay** [comment]
This one has nothing to do with windows.
The Exif refers to AF-Point "0" and it is not included in the 80d config file.

I added a check for af point existence in PR #22

**Comment by musselwhizzle** [comment]
merged. shall I close the ticket?

**Comment by rderimay** [comment]
Better no, no the plugin will show a friendly dialog instead of an lua error dialog. But basically, the config file for 80d should contain also the af point 0 which it does not

**Comment by jandhollander** [comment]
AF point 0 means that there was no AF point in focus, if I'm not mistaken. 
Possibly manually focussed?

**Comment by rderimay** [comment]
Well, at least the exif reads:
AF Area Mode : Flexizone Single

No af should be written "none" and not 0 I think

**Comment by jandhollander** [comment]
Maybe the Focus Point names start at "0" and not at "1", as I assumed.
More testing is needed, but I need to get the Focus Points to show up in the dialog before I can test this properly :(

**Comment by Knubbel** [comment]
Ok, if that was Flexizone single, I guess just a warning should be the output, since that means l**iveview CDAF autofocus** was used: http://www.dummies.com/photography/cameras/canon-camera/autofocus-options-for-live-view-and-movie-modes-on-a-canon-eos-70d/.

**Comment by jandhollander** [comment]
Aha...

I saw in the code there is already a fallback for Nikon using back-button focus. 
This scenario might need a similar fallback?

**Comment by rderimay** [comment]
i'll be working to change the whole search and display af today anyway. i'll look at it
