### ISSUE TITLE
Alphabetize "Show Metadata" 

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#23]
It would be nice if the show metadata was in abc order. Perhaps exif tool allows a -flag which controls the order. Perhaps it needs to be sorted in code.

**Comment by rderimay** [comment]
just add -sort

**Comment by musselwhizzle** [comment]
-sort seems to work for the categories only. But there's multiple categories...which I'm throwing out in the UI.

**Comment by rderimay** [comment]
I will do something.


On 6 janvier 2017 at 00:19:24, Joshua Musselwhite (notifications@github.com) wrote:

-sort seems to work for the categories only. But there's multiple categories...which I'm throwing out in the UI.

**Comment by musselwhizzle** [comment]
just remove the "-g1" tag and add sort. It fixes it.

**Comment by musselwhizzle** [comment]
https://github.com/musselwhizzle/Focus-Points/pull/25

**Comment by rderimay** [comment]
I have better I think


On 6 janvier 2017 at 00:42:20, Joshua Musselwhite (notifications@github.com) wrote:

just remove the "-g1" tag and add sort. It fixes it.

**Comment by musselwhizzle** [comment]
ok, put out a PR if you'd like
