### ISSUE TITLE
Canon - Y Axis is inverted

### ISSUE THREAD

**Issue by philmoz** [musselwhizzle/Focus-Points#35]
Line 94 of CanonDelegates.lua should be:
    local y = (imageHeight/2 - afAreaYPositions[key]) * yScale

Tested on images from 40D, 50D, 7D, 5D & 5D3.

**Comment by musselwhizzle** [comment]
Thanks for the ticket. Can you check out this branch and see if you still have the same issue: 
https://github.com/musselwhizzle/Focus-Points/tree/feature/new_ideas

**Comment by philmoz** [comment]
Yes, that's the branch with the issue.
On my Canon cameras, 0,0 is in the centre of the image. 
Positive X values are to the right, and positive Y values to the top of the image (not the bottom).

**Comment by rderimay** [comment]
Thanks ! I corrected this in the branch right now

**Comment by rderimay** [comment]
Pushed

**Comment by musselwhizzle** [comment]
When you're ready, besure to do a PR into the branch for us. Couple more days while we QA and we'll move it over into master.

**Comment by rderimay** [comment]
Ah ok. Wasn't aware that I have to pr once again

**Comment by rderimay** [comment]
I think we can close this one @musselwhizzle
