### ISSUE TITLE
FeatReq: AF-Point size and graphics type selectable in GUI

### ISSUE THREAD

**Issue by Knubbel** [musselwhizzle/Focus-Points#36]
This is not an issue, just a feature request (I did not know where else to put this):
The display of AF points in the viewfinder often does not realistically represent the size and coverage of where the camera does actually measure phase detection. Some people might prefer the rectangle shown in the viewfinder and others - especially for this plugin - might prefer to see what portion of the image was really covered by the chosen AF point in total (which usually is way more than what the viewfinder suggests).
For reference check the first blue graphics about the difference in this article: https://www.learn.usa.canon.com/resources/articles/2014/spot_AF.htmlp

Therefore I suggest to add the following two options in the plug-in's GUI in lightroom (the GUI you access under plugin manager):
a) provide the option to either **choose a rectangular shape (similar to viewfinder display) or a cross-shape** (actual cross type sensor coverage)
b) provide a **percentage scaling factor for the size of the displayed graphics,** so every user can choose to increase the size of the display to his liking (e.g. increase a cross AF display to cover the realistic area)

**Comment by musselwhizzle** [comment]
the awesome guy rderimay just wrote something to take care of this. You can beta test it here: 

https://github.com/musselwhizzle/Focus-Points/tree/feature/new_ideas

**Comment by Knubbel** [comment]
Tried and encountered the old (thought to be already solved) windows bug with the error message about not being able to oben ...-metadata.txt. 
Maybe some mixture of old and new code?

**Comment by musselwhizzle** [comment]
Oh....I'm at a loss for windows. See here the latest posts: 
https://github.com/musselwhizzle/Focus-Points/issues/11
At this point, I'm not confident it going to happen.

**Comment by rderimay** [comment]
I think we can close this one @musselwhizzle as it was opened before my code with variable size of points was checked in
