### ISSUE TITLE
Canon 5D - focus box positions is not quite right

### ISSUE THREAD

**Issue by philmoz** [musselwhizzle/Focus-Points#37]
See attached screen shot (LR at top, DPP at bottom). The scaling for the focus boxes is not correct, resulting in the boxes being displayed at the wrong place in the image.

Changing lines 31 & 32 in CanonDelegates.lua (new_ideas branch) as below fixes this.
  local imageWidth = ExifUtils.findFirstMatchingValue(metaData, { "Canon Image Width", "Exif Image Width" })
  local imageHeight = ExifUtils.findFirstMatchingValue(metaData, { "Canon Image Height", "Exif Image Height" })

I have also checked this for 40D, 50D, 7D and 5D3. For the 50D, 7D & 5D3, "Canon Image Width" == "AF Image Width" and "Canon Image Height" == "AF Image Height". For the 40D the "Canon Image Width" and "Canon Image Height" values are incorrect.
Results:
- 50D, 7D & 5D3 - can use either "Canon Image Width/Height" or "AF Image Width/Height"
- 5D - need to use "Canon Image Width/Height"
- 40D - need to use "AF Image Width/Height"

![screen shot 2017-01-07 at 8 00 23 pm](https://cloud.githubusercontent.com/assets/9474356/21740672/d4baf7b0-d514-11e6-950b-85fcb0c4b5f8.jpg)

**Comment by rderimay** [comment]
Ok interesting. 
I think we should leave "AF Image Width/Height" like in the code by default as this is the correct field for this, but we make a special case for the first 5D.
I will add this in the code.

**Comment by rderimay** [comment]
Pushed

**Comment by rderimay** [comment]
To the new-ideas

**Comment by musselwhizzle** [comment]
it's probably in your personal fork still. Whenever you're ready, PR back into this one.

**Comment by musselwhizzle** [comment]
Hey guys, if possible add samples images to this repo for all of us as well: 
https://github.com/musselwhizzle/Focus-Points-Sample-Images

**Comment by rderimay** [comment]
btw, @musselwhizzle I found this resource which absolutely grate for testing bodies we dont own :-)
http://www.rawsamples.ch

**Comment by musselwhizzle** [comment]
awesome

**Comment by rderimay** [comment]
@musselwhizzle this should have been solved a few days ago. Let's @philmoz confirm this and close this

**Comment by philmoz** [comment]
I can confirm this is now fixed in the master branch.
