### ISSUE TITLE
Pentax K-1 support

### ISSUE THREAD

**Issue by Knubbel** [musselwhizzle/Focus-Points#4]
Hi, to add support for the Pentax K-1, I suggest oyu do the following (I am not sure how to do this here):

1) add a directory called "RICOH IMAGING COMPANY, LTD"
2) add a file called "PENTAX K-1.txt" in that folder
3) add the following text in that file:

```
focusPointDimens = {300, 250}



-- numbers are makernotes:AFPointSelected  (0x000e AFPointSelected)
-- top row
1 = {2787, 1832}
2 = {3235, 1832}
3 = {3672, 1832}
4 = {4120, 1832}
5 = {4565, 1832}

-- upper row
6 = {2361, 2145}
7 = {3235, 2145}
8 = {3672, 2145}
9 = {4116, 2145}
10 = {4565, 2145}
11 = {4990, 2145}
12 = {4990, 2145}

-- center row
13 = {1900, 2450}
14 = {2350, 2450}
15 = {2787, 2450}
16 = {3223, 2450}
17 = {3687, 2450}
18 = {4120, 2450}
19 = {4560, 2450}
20 = {4994, 2450}
21 = {5446, 2450}

--lower row
22 = {2346, 2780}
23 = {2787, 2780}
24 = {3231, 2780}
25 = {3664, 2780}
26 = {4120, 2780}
27 = {4560, 2780}
28 = {4986, 2780}

-- bottom row
29 = {2794, 3100}
30 = {3235, 3100}
31 = {3650, 3100}
32 = {4105, 3100}
33 = {4553, 3100}
```

I assume it is necessary to change/enhance the core code of the plugin dependend on manufacturer, since for Pentax cameras, the relevant focuspoint information is stored in the metadata called "makernotes:AFPointSelected"  (0x000e). This is different from the Nikon metadata field.

**Comment by musselwhizzle** [comment]
Awesome. Thanks. Would you mind attaching a raw file for me so I can see the metadata and play around with this. The code will most likely need some updates as I don't think "33" is a valid property type. I'll work on adding it for you though.

**Comment by Knubbel** [comment]
You can take any files from dpreviews studio scene comparison, such as this JPG here: https://www.dpreview.com/reviews/image-comparison/download-image?s3Key=6f225c8c22ca48c9bc25c582f9981382.jpg where the center point was chosen.

On Pentax DSLRs the AF points actually always are named by a simple number such as "1" or "5" or "33", where on Nikon you have the "A1" and "D8" and so on. The num,bering scheme also is quite simple on all models since they always start the "1" on the top row left corner and increment as you read to the right and down. See Phil Harveys documentation here: http://exiftool.sourceforge.net/TagNames/Pentax.html

On a more general note I suggest for a later release you consider a routine to adjust things if the used creates a JPG with a resolution lower than maximum, e.g. 16 MPx instead of 36 MPx. The absolute pixelcounting currently suggests it works only on uncropped full res images.

Thanks for your great work.

**Comment by Knubbel** [comment]
By the way, I got to the data in a quick way:
1) Google for a viewfinder overlay image for your camera, such as this one: https://1.bp.blogspot.com/-DRWu2YmqHcg/UeNOnX0OtjI/AAAAAAAABaU/68Oz7X-Svf0/s1600/Nikon+D7100+AF.jpg
2) Show it on your computer screen screen maximised
3) Take one JPG image of your computer screen with your camera where you frame it exactly fitting
4) Display your photo JPG in a viewer like XnView which does show the exact mouse pointer coordinates
5) just point the mouse over each AF point and take a note of this

**Comment by Knubbel** [comment]
And here are more raws and full metadata images to play around with:
http://www.imaging-resource.com/PRODS/pentax-k1/pentax-k1GALLERY.HTM
and
http://www.photographyblog.com/previews/pentax_k1_photos/
and
https://www.dpreview.com/samples/8631711489/pentax-k-1-real-world-sample-gallery
and
http://www.d-pixx.de/2016/07/pentax-k-1-test/
and

**Comment by musselwhizzle** [comment]
until i have a chance to test it, you can take a look here and see if it works as expected. 
https://github.com/musselwhizzle/Focus-Points/tree/feature/pentax

**Comment by Knubbel** [comment]
Hm. I do get an error 1 as it says, the plug-in is for LR v6 only.
I only have LR v5.7.1 here.
Is the plug-in really dependend on v6 specific functionality? That might exclude quite a number of people from using it.

**Comment by musselwhizzle** [comment]
i lowered the required version to 5. download again and try. Let me know if the whole application still works. I only have LR 6 so I can't test.

**Comment by Knubbel** [comment]
Thanks. I now can start the plugin. But when calling it I get an error pop-up:
**"Internal error. Couldn't open file [image]-metadata.txt for reading."**
Running Windows 7 64bit if that has any impact.

**Comment by musselwhizzle** [comment]
Would you download this version which has logging enabled:
https://github.com/musselwhizzle/Focus-Points/tree/feature/windows_path

and paste the logs in here. According to the docs, the log is located in "your My Documents folder."

**Comment by Knubbel** [comment]
Thanks, I will run that in a minute. First I would like to share something I found on Adobe forums, which might be helpful here as it is about funny LR Lua syntax:

> on Windows systems, LrTasks.excecute() is tricky:
> - substitute \ by \\\ (this is a Lua issue)
> - surround each pathname that has a space in it with double-quotes (")
> - substitute  > by ^> 
> - in addition, surround the whole commandline with double-quotes
> 
> Besides that your program path doesn't look correct. It should be:
> C:\programs\dcrawps64.exe
> and therefore in your Lua code, you have to use:
> C:\\\programs\\\dcrawps64.exe
>

**Comment by Knubbel** [comment]
The only log file I found after installing your new version is "libraryLogger.log" and it contains three lines:

> 01/05/2017 11:27:13 WARN	starting plugin 
> 01/05/2017 11:27:13 WARN	writing metadata file to: E:\85 Downloads\K_1_1502-metadata.txt 
> 01/05/2017 11:27:13 WARN	exif command: 'C:\Programme_Portabel\LR-Plugins\focuspointswin.lrplugin\bin\exiftool\exiftool' -a -u -g1 'E:\85 Downloads\K_1_1502.JPG' > 'E:\85 Downloads\K_1_1502-metadata.txt' 

No file of the name "K_1_1502-metadata.txt" is on the drive.

**Comment by musselwhizzle** [comment]
Ok thank you. Some people are working on the issue over here on this ticket. https://github.com/musselwhizzle/Focus-Points/issues/11#issuecomment-270522519

I'm confident it'll be figured out soon :)

**Comment by Knubbel** [comment]
Cool. Just give a message, once that is solved.

**Comment by musselwhizzle** [comment]
windows is kind of resolved-ish. It's the best it's going to get for now (which is no good....) 
If you're able to verify the plugin at least attempts to put the focus spots in the right place, that would be great.
