### ISSUE TITLE
Cropped on a Rotate 90 CW is incorrect focus point

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#48]
There's a new bug that's been introduced with the new code. If a photo was shot at "Rotate 90 CW" and then cropped from what's the human bottom, left the focus point is wrong.

**Comment by rderimay** [comment]
Please provide an example file / screen shot.

**Comment by musselwhizzle** [comment]
Error 
<img width="484" alt="screen shot 2017-01-08 at 11 19 11 am" src="https://cloud.githubusercontent.com/assets/2308674/21752848/93d22b1c-d594-11e6-850f-8bdca6768af5.png">

crop shown
<img width="481" alt="screen shot 2017-01-08 at 11 19 22 am" src="https://cloud.githubusercontent.com/assets/2308674/21752849/97a6c360-d594-11e6-954d-729c04b335a5.png">

uncropped
<img width="481" alt="screen shot 2017-01-08 at 11 19 22 am" src="https://cloud.githubusercontent.com/assets/2308674/21752853/9d7641b2-d594-11e6-9bbc-dcb335acbd54.png">

**Comment by project802** [comment]
No crop or rotation:
![original_correct](https://cloud.githubusercontent.com/assets/24799979/21752851/bdb98dc6-d5ad-11e6-871e-3cccccc773ba.png)

Basic crop/rotation around the center point:
![rotated_cropped_incorrect](https://cloud.githubusercontent.com/assets/24799979/21752852/bdbba32c-d5ad-11e6-9fd6-8e757e79586d.png)

**Comment by rderimay** [comment]
Thanks will look at it.
The transformation code is anyway not clean for me. 

No idea what I changed there to make it not work anymore. Maybe this is related to the new json decoding.

**Comment by musselwhizzle** [comment]
this is on current master.

**Comment by rderimay** [comment]
ah ok. better then.

**Comment by project802** [comment]
If you need it, the NEF from my example above is now in the Focus-Points-Sample-Images master.

**Comment by musselwhizzle** [comment]
@rderimay if you work on this, please work off of the current master and not any outstanding PRs. This is a separate issue, standalone. It can be merge into other things.

**Comment by rderimay** [comment]
Cannot make a new PR until PR #47 is accepted (or not) @musselwhizzle.
Should you just pick stuff, let me know what and what not please.

**Comment by musselwhizzle** [comment]
checkout a new repo and work off of master. In the mean time, read this to help with your git flow: 
https://github.com/musselwhizzle/Focus-Points/blob/master/Contributing.md

**Comment by musselwhizzle** [comment]
So my bug report is inaccurate and I'm going to close the ticket. Basically, originally the image was upside down and I (apparently) rotated it to turn it right side up. Since LR doesn't report rotations, the values are off. 

I'm closing the ticket.

**Comment by project802** [comment]
The image I attached is straight out of the camera. Rotating it in LR shows the above error. New issue or reopen?

**Comment by project802** [comment]
Is #53 where this is now tracked?

**Comment by rderimay** [comment]
Yes, I will track this at the same time, I have to redo the math to accommodate the fact that a user can also rotate on grid

**Comment by musselwhizzle** [comment]
@project802 i reopened the issue and will help verify on your file. Can you please link directly to the RAW file for testing.

**Comment by musselwhizzle** [comment]
@rderimay - assume this is a non issue until we get the file and I can verify.

**Comment by project802** [comment]
I'm on mobile but the file is in the sample images under D800 and it's the portrait one. Just pulled in yesterday I think.

**Comment by musselwhizzle** [comment]
i dont see any sample images: 
https://github.com/musselwhizzle/Focus-Points-Sample-Images/tree/master/Canon

**Comment by project802** [comment]
https://github.com/project802/Focus-Points-Sample-Images/blob/master/Nikon/D800/D800-C9-90deg.NEF

**Comment by musselwhizzle** [comment]
Verified, but let me make a separate ticket since it's a bit different. Once specific to this issue.

**Comment by musselwhizzle** [comment]
https://github.com/musselwhizzle/Focus-Points/issues/55
