### ISSUE TITLE
User chosen rotation is not taken into account

### ISSUE THREAD

**Issue by rderimay** [musselwhizzle/Focus-Points#53]
Whenever the user chooses to rotate his picture in the grid mode, the current algorithm ignores it.
I found a way to get the info from lightroom and would like to implement it.

**Comment by musselwhizzle** [comment]
assigned to you. have at it.

**Comment by rderimay** [comment]
Much better way of working on stuff this way. Before you never new if someone else would have started to work on this also...

**Comment by musselwhizzle** [comment]
should make it a lot easier on me to QA. I only have to QA 1 thing instead of the whole app as well.

**Comment by musselwhizzle** [comment]
Using photo https://github.com/project802/Focus-Points-Sample-Images/blob/master/Nikon/D800/D800-C9-90deg.NEF

when a user rotates the photo during a crop, the focus point is off. See screens for reference

<img width="516" alt="screen shot 2017-01-09 at 9 53 17 am" src="https://cloud.githubusercontent.com/assets/2308674/21776902/95c1390a-d651-11e6-96aa-9a9cf16e6b37.png">
<img width="540" alt="screen shot 2017-01-09 at 9 53 50 am" src="https://cloud.githubusercontent.com/assets/2308674/21776905/97ba869e-d651-11e6-9bc4-e8d7d96b7b00.png">

**Comment by mkjanke** [comment]
Similar issue with photos taken in portrait orientation [Olympus]. Focus point is displayed as though image was landscape orientation.

'Orientation' tag in metadata shows 'Rotate 270 CW'.

Using grid view to rotate photo displays correct focus point location .

Sample image:
[https://github.com/mkjanke/Focus-Points-Sample-Images/blob/master/Olympus/E-M1MarkII/P1080121.ORF]

Focus point should be directly on the bird. 

As displayed:
![screen shot 2017-01-09 at 6 08 33 pm](https://cloud.githubusercontent.com/assets/24959147/21788884/d7032f50-d696-11e6-9f2f-c4c3cdbe7058.png)

Correct focus point location:

![screen shot 2017-01-09 at 6 08 54 pm](https://cloud.githubusercontent.com/assets/24959147/21788901/f1f43b1a-d696-11e6-950c-adb607dc7f24.png)

Is this a new issue, or is this a manifestation of this issue? If new, I'll create as new.

**Comment by rderimay** [comment]
this is #55

**Comment by musselwhizzle** [comment]
those are different issues. I see this tickets saying: 
If you rotate the photo in lightroom, lightroom doesn't report if it's been rotated and thus the focus point is wrong. 

I see #55 as saying, rotation during crop isn't working for that photo. I could repo for that 1 photo, but not for mine.

**Comment by rderimay** [comment]
What I meant, is that the source of the problem is the same in my code. You can let them both open so we can track

**Comment by musselwhizzle** [comment]
> I found a way to get the info from lightroom and would like to implement it.
You've found a way that Lightroom will report if I've rotated a photo in library mode or develop mode?

**Comment by rderimay** [comment]
yes. Better said, it seems that the value takes the Exif value and builds on it depending on what you do.
INCLUDING mirroring...

**Comment by rderimay** [comment]
Solved in #73
