### ISSUE TITLE
Rotation during crop on vertical image is incorrect

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#55]
Using photo https://github.com/project802/Focus-Points-Sample-Images/blob/master/Nikon/D800/D800-C9-90deg.NEF

when a user rotates the photo during a crop, the focus point is off. See screens for reference

<img width="516" alt="screen shot 2017-01-09 at 9 53 17 am" src="https://cloud.githubusercontent.com/assets/2308674/21776902/95c1390a-d651-11e6-96aa-9a9cf16e6b37.png">
<img width="540" alt="screen shot 2017-01-09 at 9 53 50 am" src="https://cloud.githubusercontent.com/assets/2308674/21776905/97ba869e-d651-11e6-9bc4-e8d7d96b7b00.png">

**Comment by musselwhizzle** [comment]
closing this as duplicate ticket.

**Comment by rderimay** [comment]
you can assign it to me anyway

**Comment by musselwhizzle** [comment]
yours.

**Comment by rderimay** [comment]
Solved in #73
