### ISSUE TITLE
Refactor metadata to be a table rather than a string

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#57]
Currently the metadata is read from a file and returned as a string. Any method that then needs the metadata must create it's own table from it. Instead, in DefaultPointsRenderer, convert this string into a table of key, value pairs and store it. (Note, dont do this in the metadata viewer as converting to a table will throw out duplicate key names). The metadata table (and not string) should then be passed to methods and not the string metadata.

E.g.
```
local metadata = {}
metadata["AF Point"] = "C6"
metadata["Focal Length"] = "30mm"
```

**Comment by rderimay** [comment]
ok 'll take it

**Comment by rderimay** [comment]
PR #59

**Comment by musselwhizzle** [comment]
awesome!
