### ISSUE TITLE
Does not support live view contrast detect AF on Nikon

### ISSUE THREAD

**Issue by project802** [musselwhizzle/Focus-Points#65]
On my D800 while using live view, you can select an arbitrary focus point for contrast detection instead of having to use the AF sensor points.  In this case, the plugin doesn't parse the required metadata for displaying the AF point.  

I recommend copying the default delegate parser into a Nikon delegate file and add this support to the getAfPoints() function. 

Please assign to me so I can submit a PR on a feature branch for this issue.

**Comment by musselwhizzle** [comment]
Can't you just add the metadata to the fallback points?

**Comment by project802** [comment]
This is an architectural decision that has to be made.  Since this is a Nikon specific behavior the question then becomes is Nikon the "default" behavior or should it have a specific delegate like the other makes.  Let me know which direction you want and I'll make the PR.

**Comment by musselwhizzle** [comment]
From the description, it sounds like simply adding another fallback that could be added for nikon cameras. Feel free to put some images into https://github.com/musselwhizzle/Focus-Points-Sample-Images which display this behavior. Link to them in here and then describe what should be shown.

**Comment by musselwhizzle** [comment]
you could also take a stab at it and then we could do some clean up work as needed.

**Comment by project802** [comment]
When using the AF sensor, the "AF Area Mode" is set to "Dynamic Area" and the regular logic for using "AF Points Used" and "Primary AF Point" apply.  

Under contrast detect with Live View, "AF Area Mode" is "Contrast-detect (normal area)" and the regular metadata is empty.  Instead, the AF point is populated using "AF Area X Position" and "AF Area Y Position".  Additionally, the width and height are in "AF Area Width" and "AF Area Height", respectively.  

For example:
https://github.com/musselwhizzle/Focus-Points-Sample-Images/blob/master/Nikon/D800/D800-contrast1.NEF 

The focus point is at the 3'oclock position on the volume knob, close to where it intersects the chassis.

**Comment by project802** [comment]
I'll add it to the default delegate and make the PR.  Since its a feature branch and a small change, a follow-on issue can be made to break it out into a Nikon delegate or do other work based on it.

**Comment by musselwhizzle** [comment]
ok, sounds pretty similar to what the Fuji and other cameras are doing. Be sure to test vertical in both directions as well. You up for taking a crack at it? If the focus point is null, you can delegate back over to DefaultDelgate.

**Comment by project802** [comment]
That sounds like a better idea...make a Nikon delegate that looks for contrast and then defaults if none is found?  I can do any one of the discussed three ideas since I already have code to find it (its really short).  Which one do you want me to PR?

**Comment by musselwhizzle** [comment]
You can do a PR and i'll move it to a feature branch and test on my cameras for a while. From there, we'll merge over after a QA period. I'm not going to work today so I'll get to it tomorrow.

**Comment by musselwhizzle** [comment]
Need to test with NEF files of the camera shot at 90 CW and 90 CCW then will merge into master

**Comment by project802** [comment]
I've submitted a PR in the sample images repo with one example.  I can take another tonight.

**Comment by musselwhizzle** [comment]
I shot some images and verified it. Good code. Good catch!
