### ISSUE TITLE
Add a dialog button for switching logging on or off.

### ISSUE THREAD

**Issue by rderimay** [musselwhizzle/Focus-Points#69]

**Comment by musselwhizzle** [comment]
it's possible you may need to package it with sqlite. I'm not positive...

**Comment by rderimay** [comment]
No idea, never done it before. We will see...


On 10 janvier 2017 at 19:51:39, Joshua Musselwhite (notifications@github.com) wrote:

it's possible you may need to package it with sqlite. I'm not positive...

**Comment by musselwhizzle** [comment]
for what it's worth, if you down load other people's plugin, just change the folder name then can you see what they put in their "bin". If you want to peak at the code if it's compiled use this: 
https://sourceforge.net/projects/unluac/

**Comment by musselwhizzle** [comment]
optional ideas: 
https://github.com/musselwhizzle/Focus-Points/issues/71

**Comment by project802** [comment]
Working on this already?  I know how to add a dialog to the plugin manager and use the preferences framework.  I can whip up a PR.

**Comment by project802** [comment]
Here is an example https://github.com/project802/Focus-Points/tree/feature/prefs_pane let me know if you want me to PR it.

**Comment by musselwhizzle** [comment]
I'm going to let @rderimay make that call. The work was promised to him. I see no issue with putting a PR up. Whether or not the exact PR is used, I'm sure there's good code and ideas there to be had and shared.

**Comment by project802** [comment]
Yea no worries at all.  Its a super basic example of the prefs usage and plugin box that takes the guesswork out of chasing the API docs.  I did it on a feature branch hoping that someone with more time can make it polished.  It would be nice to have all the prefs in a central location and initialized there as well so that it isn't spread all over the code.

**Comment by rderimay** [comment]
Very good, thanks @project802 !
@musselwhizzle, if you want, you could make accept it.
Assign me to issue #71 about expanding the logger. I will introduce levels of logging like discussed and replace the on/off button in the new pref dialog pane by a level selector, that's fine.

**Comment by musselwhizzle** [comment]
the code was merged into a feature branch here: 
https://github.com/musselwhizzle/Focus-Points/tree/feature/prefs_pane
