### ISSUE TITLE
Focus Points Plugin clips on Windows

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#70]
The plugin mostly works on windows, minus this clipping issue (see screenshot). I'm not sure there's any way around this other than using imagemagick to bypass Lightroom rendering. 

<img width="1149" alt="screen" src="https://cloud.githubusercontent.com/assets/2308674/21820220/b6bcc412-d723-11e6-86b2-0dc2038410fe.png">

**Comment by rderimay** [comment]
Yeah. After spending literally hours yesterday of trying the cheat LR in all directions I could think of, I am pretty pessimistic now...

**Comment by musselwhizzle** [comment]
I'm pretty sure we'll need imagemagick.

**Comment by rderimay** [comment]
Yeah. That seems pretty buggy.
My major fear with ImageMagick or GraphicsMagick is not to make a script, I made a lot of scripts with it and thats pretty straight forward. The current code can be easily branched to generated a IM script when on PC.
My major fear is how to embed it with the plugin and have a stable stuff without installation problems etc.
Maybe you have experience with that.


On 13 janvier 2017 at 19:21:37, Joshua Musselwhite (notifications@github.com) wrote:

I'm pretty sure we'll need imagemagick.

**Comment by musselwhizzle** [comment]
My **_guess_** was to write a temporary images parallel (like I was doing for the metadata) and have the ```viewFactory:picture``` read it from the uri. That could be easily tested with any current jpeg on the hard drive.

**Comment by rderimay** [comment]
I tried the following simple view struct based on one jpg and an icon, and it fails as well.
````
viewFactory:view {
      viewFactory:picture {
        value = _PLUGIN:resourceId("assets/imgs/_focus_point_red-fat_center.png"),
        background_color = LrColor(1, 1, 1, 0)
      }, 
      viewFactory:picture {
        width = 600, 
        height = 400,
          value = _PLUGIN:resourceId("assets/IMG_8576.jpg")
      }, 
      place = 'overlapping', 
    }
````

I tried without background_color and with background_color = LrColor() or LrColor(1, 1, 1, 0) which should be transparent. Result is the same.
The only thing that work is when background_color is a none transparent color. And this does not help us that much...

**Comment by musselwhizzle** [comment]
TODO: instead of using margin_left/margin_top, R&D using a viewFactory:spacer.

**Comment by musselwhizzle** [comment]
TODO: 

> The only thing that work is when background_color is a none transparent color

R&D setting the alpha to .01 and seeing if it's "better than nothing"

**Comment by musselwhizzle** [comment]
RE: alpha color on windows. 

It appears the heart of the problem is that windows doesn't support transparency as shown here; 

`local view = viewFactory:view {
    viewFactory:picture {
      value = _PLUGIN:resourceId(fileName)
    },
    margin_left = x - anchorX,
    margin_top = y - anchorY,
    background_color = LrColor(1, 0, 0, 1)
  }`
With this code, the picture has a red background. Changing the alpha of LrColor to anything other than "1" such as ".99" isn't support and causes LR on windows to render as a solid color.

**Comment by musselwhizzle** [comment]
RE: instead of using margin_left/margin_top, R&D using a viewFactory:spacer.

Spacers have the same issue as the margin. LR for windows just can't have transparent backgrounds on views that overlap. 

Conclusions: at this time, I see no other option than imagemagick to bypass the bugs in LR for windows.

**Comment by musselwhizzle** [comment]
I tired 2 more things, both failed
Idea 1: instead of using padding, put a transparent image over the targetPhoto and let the transparency in the raster photo have the padding. Windows on LR would not render this either. Same issues, no transparency anywhere is supported. Not even PNGs. (see screen attached)

Idea 2: use ```targetPhoto:requestJpegThumbnail``` to generate a jpeg of the image and then just composition the focus points over it using mogrify. Again this would work in mac but on Windows, the image is horribly distorted. targetPhoto:requestJpegThumbnail is known to be buggy. (see attached)

At this point, I'm completely out of ideas and most likely will not attempt further progress. Outside help is welcomed. 

<img width="1322" alt="screen shot 2017-03-12 at 1 11 09 pm" src="https://cloud.githubusercontent.com/assets/2308674/23835522/091ff8c8-0726-11e7-8472-9e24a7e37a2f.png">
![dsc_4596 nef-thumb](https://cloud.githubusercontent.com/assets/2308674/23835524/0b2e340e-0726-11e7-9c13-518bfe949e8d.jpeg)

**Comment by capricorn8** [comment]
Obviously also LR7 does not change anything, the plugin still shows the mentioned issue.
Or is there any silver lining on the horizon that this plugin may work also on Windows some day?
Unfortunately, my LUA expertise too limited to actively support.

**Comment by jrsforums** [comment]
Perhaps you can get with this guy to get working on Windows...
http://www.lightroomfocuspointsplugin.com

**Comment by capricorn8** [comment]
Another 18 months later, in which we have seen multiple updates to LR, its SDK and also Windows - but still this issue remains. I have spent a few hours to understand the code, tried this and that, but no success. I also haven't been able to figure out why the corners of the AF point are incomplete. Eg. for my Olympus files, I always get the two rightmost corners only:
![Olympus_Example](https://user-images.githubusercontent.com/33000800/63186824-a8eb5f80-c05d-11e9-8f53-285b124dde6b.jpg)
Same for Canon, except the not selected AF points which miss only 1 corner ;-)
![Canon_Example](https://user-images.githubusercontent.com/33000800/63186859-c0c2e380-c05d-11e9-90c6-257ef2f901db.jpg)

Would be nice to find a way to at least fix this; I have started to use the plugin's output and overlay this with the photo in PS. 

Any idea how to tackle this one? The debug log shows that DefaultPointRenderer.createPointView is being called 5x (center + 4 corners) picking the proper imgs files but for some reason two of them don't show up in the created view.

Thanks for any suggestions.

**Comment by musselwhizzle** [comment]
I doubt this is going to get any motion as it's already been several years now. You could always try learning LUA and seeing if you can tackle it. Or perhaps contact adobe and see if they'll fix the Windows bugs in Lightroom.

**Comment by ropma** [comment]
I've build a small prototype (https://github.com/ropma/LrDisplayWithMogrify) using the mogrify approach. I think the problem for the distorted image was a missing binary flag in the file open.
With "w+b"  it seems to work - at least in the prototype.

I'm currently a little bit busy, but after my vacation in September I can try to create a Focus point version using mogrify.

**Comment by capricorn8** [comment]
> I'm currently a little bit busy, but after my vacation in September I can try to create a Focus point version using mogrify.

This looks very promising! Looking forward to seeing this integrated with the plug-in. And I'm curious about your findings regarding missing AF field corners.

**Comment by musselwhizzle** [comment]
@capricorn8 - https://github.com/musselwhizzle/Focus-Points/tree/windows_support

give it a shot

**Comment by musselwhizzle** [comment]
master now has support for windows. issue is closed
