### ISSUE TITLE
Update README file to list out Canon Cameras if possible

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#74]
Let's update the readme file to be more explicit about what canon cameras we support.

**Comment by musselwhizzle** [comment]
also, update the "adding your camera" section. People should check the metadata viewer to see if they camera reports dynamically before having to map it all out by hand.

**Comment by philmoz** [comment]
I have tested the following Canon cameras:
DSLR phase detect AF - 350D, 40D, 50D, 7D, 5D & 5DIII
DSLR contrast detect (live view) AF - 5DIII
P&S contrast detect AF - G12, G1X & G5X

The P&S cameras work, except that the Y co-ordinate if inverted (separate issue raised).
