### ISSUE TITLE
Fuji focus point wanders during heavy crop

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#8]
During a heavy crop, the focus point wanders a little bit off. It's possible it's related to the focus point dimens not being the correct size, or that the focus box is treating the point at top,left rather than as the middle point which is probably is.

**Comment by DeziderMesko** [comment]
Dimensions of focus "box" are not fixed. You can see it on this video: https://www.youtube.com/watch?v=rV0xqR8RDsU so, some small default like 100x66 is probably best way to solve it. I checked other EXIF tags, and I havn't found any other tag which could refer to the size of the box. 

In the meantime I've looked into exif of X-T1, X-E2S, X100S and all contain Focus Pixel tag. However I still have the issue with focus point completely out of picture for every picture. Is it fine for you? If so, maybe LR5 is the problem?

**Comment by musselwhizzle** [comment]
Unfortunately, I dont have much way of testing as it's not my camera. Try the lastest mater and see if you still have issues. "rderimay" just did a ton of work to support Fuji cameras.

**Comment by rderimay** [comment]
The points being not correctly drawn under rotation and heavy crop is resolved imo
