### ISSUE TITLE
photo:getRawMetadata("orientation") fallback for LR 5

### ISSUE THREAD

**Issue by musselwhizzle** [musselwhizzle/Focus-Points#84]
musselwhizzle 14 hours ago • edited Owner
This method isn't available in LR 5. what are we going to do about LR 5 users? Just make the plugin work on LR 6 (current) and above?

Would be nice to check for the version and fall back to the metadata orientation at least so we can still support LR 5.

@rderimay  9 hours ago Contributor
Mh. I think in case getRawMetadata("orientation") returns NIL, we could simply default back to the old method of checking using the exifs.
I'll make an issue for that, please assign it to me and I'll take care of it

**Comment by rderimay** [comment]
This should be already solved in the current master after the last merge:

````
function DefaultPointRenderer.getUserRotationAndMirroring(photo)
  local userRotation = photo:getRawMetadata("orientation")
  if userRotation == nil then
    logWarn("DefaultPointRenderer", "userRotation = nil, which is unexpected starting with LR6")
    return 0, 0
  elseif userRotation == "AB" then
    return 0, 0
  elseif userRotation == "BC" then
    return -90, 0
````

**Comment by musselwhizzle** [comment]
where's the fallback?

**Comment by rderimay** [comment]
Sorry, should be the case in PR #86
