### ISSUE TITLE
Canon - Y axis revisited

### ISSUE THREAD

**Issue by philmoz** [musselwhizzle/Focus-Points#88]
The Y co-ordinate for Canon DSLR cameras is now correct (positive towards the top of the image).

However it seems for some (maybe all) Canon P&S cameras the Y co-ordinate goes the other way :(
Tested on G12, G1X & G5X raw images.

I've attached a patch that fixes this for the above 3 cameras only.

[canon_powershot.txt](https://github.com/musselwhizzle/Focus-Points/files/703034/canon_powershot.txt)

**Comment by musselwhizzle** [comment]
* Do you know how to create a Pull Request or do you just want me to try and merge this code in myself?

* Can you see of anyway to dynamically tell if it's a point and shoot camera rather than just searching for every P&S name?

**Comment by philmoz** [comment]
I can create a pull request, just haven't had time to create a fork.

My patch only works for the three cameras I listed - there is probably a better way to do this, I included it for reference in case it made things clearer.

**Comment by musselwhizzle** [comment]
ok thanks. i'll take over from here then

**Comment by philmoz** [comment]
Also applies to JPEG images taken with IXUS 310 HS & SX40 HS cameras.
I suspect this applies to all Canon P&S cameras.

Not sure how to deal with this - there are a huge number of P&S camera models from Canon.

**Comment by musselwhizzle** [comment]
is there anything in the metadata that would give a reliable indication of P&S vs dslr? "Camera Type" == "Compact" maybe?

**Comment by philmoz** [comment]
"Camera Type" == "Compact" works for all the test images I have tried so far.

**Comment by musselwhizzle** [comment]
Mind looking at this PR and making sure this is correct: 
https://github.com/musselwhizzle/Focus-Points/pull/89/files

**Comment by philmoz** [comment]
Looks good. It is worth converting the type to lower case and comparing to "compact" - just in case?

**Comment by musselwhizzle** [comment]
sure. 

FYI, I dont have any Canon dslr images to test where the focus point isn't center. You've tested this right?

**Comment by philmoz** [comment]
Yes. All my test images (DSLR, and P&S) work as expected with this fix.
I've listed the cameras I've tested in the issue about updating the supported Canon models.

**Comment by musselwhizzle** [comment]
ok, I think this just about supports every canon camera then... nice job!
Merging in a minute
