### ISSUE TITLE
Dialog window too tall - 'Ok' button is hidden in some cases.

### ISSUE THREAD

**Issue by philmoz** [musselwhizzle/Focus-Points#90]
The calculation of the photo size in the dialog window (FocusPointsDialog.calculatePhotoDimensions), should check if the photo size fits in the calculated content size.

Depending on the aspect ratio of the LR window compared to the image dimensions this can result in the dialog being larger than the screen height, and the 'OK' button is not visible.

Patch attached, this also increases the content size slightly to use more of the screen.
[windowsize.txt](https://github.com/musselwhizzle/Focus-Points/files/703220/windowsize.txt)

**Comment by musselwhizzle** [comment]
Mind forking and PR? It's harder for me to merge it this way.

**Comment by musselwhizzle** [comment]
fixed
