### ISSUE TITLE
R&D: Use command output instead of intermediary file

### ISSUE THREAD

**Issue by rderimay** [musselwhizzle/Focus-Points#99]
Joshua, maybe you tried that before or you know the answer immediately.
For now, when we extract the Exif, we create a file "-metadata.txt" beside the original photo.
I feel this to be not ideal because of all possible problems we could get into like read only directory, shared folder, etc.
Maybe we can find a way to read directly from the command output instead of creating a temporary file.

**Comment by musselwhizzle** [comment]
Sure, take a look into it.

**Comment by rderimay** [comment]
PR #105
